apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf-admin-role
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default
roleRef:
  kind: ClusterRole
  name: telegraf-admin-role
  apiGroup: rbac.authorization.k8s.io

