apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deployment
  labels:
    app: my-node
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
      - name: my-node-container
        image: josanescod/node-simple-app:1.0
        ports:
        - containerPort: 3000
    