apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
type: Opaque
data:
  password: "cGFzc3dvcmQ=" 
  sudo_password: "cm9vdA=="
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/josan/demo7/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      nodeName: worker1
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: password
        - name: DEFAULT_WORKSPACE
          value: "/config/workspace"
        - name: SUDO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: sudo_password
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: codeserverdata
          mountPath: "/config"
      volumes:
      - name: codeserverdata
        persistentVolumeClaim:
          claimName: codeserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
spec:
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8443


