- name: Install k3s
  hosts: controlplane, worker1
  tasks:
    - name: Download k3s binary
      get_url:
        url: https://github.com/k3s-io/k3s/releases/download/v1.28.2%2Bk3s1/k3s
        dest: /usr/local/bin/k3s
      become: yes
    
    - name: Changing permissions
      file:
        path: /usr/local/bin/k3s    
        mode: '+x'
      become: yes

    - name: Configure kubectl alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc" 
        line: "alias kubectl='k3s kubectl --'"          
        insertafter: EOF
      when: ansible_user != 'root'
      become: yes

 
    

    