- name: Install open-lens
  hosts: localhost
  tasks:
    - name: Download open-lens
      get_url:
        url: https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.5.2-366/OpenLens-6.5.2-366.amd64.deb
        dest: /home/vagrant/OpenLens-6.5.2-366.amd64.deb

    - name: Running script
      apt:
        deb: /home/vagrant/OpenLens-6.5.2-366.amd64.deb
      become: yes

    - name: Delete OpenLens-6.5.2-366.amd64.deb
      file:
        path: /home/vagrant/OpenLens-6.5.2-366.amd64.deb
        state: absent
      become: yes
    
    
    