- name: Install kind
  hosts: controlplane, worker1
  gather_facts: no
  become: yes

  tasks:
    - name: Download Go binary
      get_url:
        url: "https://go.dev/dl/go1.21.4.linux-amd64.tar.gz"
        dest: "/tmp/go1.21.4.linux-amd64.tar.gz"

    - name: Extract Go binary
      ansible.builtin.unarchive:
        src: "/tmp/go1.21.4.linux-amd64.tar.gz"
        dest: "/usr/local"
        remote_src: yes
        creates: "/usr/local/go"

    - name: Add Go binary path to profile
      lineinfile:
        path: "/home/vagrant/.profile"
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: yes
        state: present

    - name: Source updated profile and test Go version
      shell: . /home/vagrant/.profile && go version  
    
    - name: Reset connection so docker group is picked up.
      meta: reset_connection  
   
    - name: Install Kind
      command: /usr/local/go/bin/go install sigs.k8s.io/kind@v0.20.0
      
    - name: Move Kind binary to /usr/local/bin
      command: mv /root/go/bin/kind /usr/local/bin/

    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

       
