- name: Copy YAML directory to remote machine
  hosts: controlplane  
  become: yes  

  tasks:
    - name: Copy the 'yaml' directory to the remote machine
      copy:
        src: ../yaml
        dest: /home/vagrant/
        owner: vagrant
        group: vagrant
        mode: 0755