- name: Install Sealed Secrets
  hosts: controlplane
  tasks:
  - name: Download and Extract Kubeseal binary
    unarchive:
      src: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.4/kubeseal-0.24.4-linux-amd64.tar.gz"
      dest: "/usr/local/bin"
      remote_src: yes
      creates: "/usr/local/bin/kubeseal"
    become: yes

  - name: Set execute permissions for Kubeseal binary
    file:
      path: /usr/local/bin/kubeseal
      mode: '+x'
    become: yes

  - name: Download Sealed Secrets controller.yaml
    get_url:
      url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/controller.yaml
      dest: "/home/{{ ansible_user }}/Sealed-Secrets-Controller.yaml"

  - name: Print message to console
    shell: "echo 'INFO: execute kubectl apply -f controller.yaml in your k8s cluster'"

  - name: Installing other tools (batcat)
    apt:
      name: bat
      state: present
    become: yes

  - name: Configure batcat alias
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      line: "alias cat='batcat'"
      insertafter: EOF
    when: ansible_user != 'root'
    become: yes

  - name: Installing other tools tree
    apt:
      name: tree
      state: present
    become: yes


