apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My HTML Page</title>
    </head>
    <body>
      <h1>Test Ingress Nginx amb External-IP</h1>
      <p>Funciona correctament.</p>
    </body>
    </html>
