apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap2
data:
  config.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: example-config
    data:
      key1: clau1
      key2: value1
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My HTML Page</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
    </body>
    </html>
