apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: container1
    image: nginx:alpine
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
    envFrom:
    - configMapRef:
        name: my-configmap
    - secretRef:
        name: my-secret-2
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap2
      items:
      - key: index.html
        path: index.html
