apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: container1
    image: nginx:alpine
    envFrom:
    - configMapRef:
        name: my-configmap
    - secretRef:
        name: my-secret

