apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: container1
    image: nginx:alpine
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
    envFrom:
    - configMapRef:
        name: my-configmap
        # - secretRef:
        #     name: secret2
        # - secretRef:
        #     name: secret3
        # - secretRef:
        #     name: secret4
    # - secretRef:
    #     name: my-secret-test
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap2
      items:
      - key: index.html
        path: index.html
