- name: Install k0s
  hosts: controlplane, worker1
  tasks:
    - name: Download k0s script
      get_url:
        url: https://get.k0s.sh
        dest: /home/vagrant/k0s.sh

    - name: Running script
      shell: |
        sh /home/vagrant/k0s.sh
      become: yes

    - name: Delete k0s.sh
      file:
        path: /home/vagrant/k0s.sh
        state: absent
      become: yes
    
    - name: Configure k0s alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc" 
        line: "alias kubectl='k0s kubectl'"          
        insertafter: EOF
      become: yes

    - name: Download k0sctl
      get_url:
        url: https://github.com/k0sproject/k0sctl/releases/download/v0.16.0/k0sctl-linux-x64
        dest: /home/vagrant/k0sctl-linux-x64    

    - name: Changing permissions
      file:
        path: /home/vagrant/k0sctl-linux-x64    
        mode: '+x'
      become: yes

    - name: Move k0sctl binary to /usr/local/bin
      command: mv /home/vagrant/k0sctl-linux-x64 /usr/local/bin/k0sctl
      become: yes

    