- name: Install Minikube
  hosts: all  
  tasks:
    - name: Download Minikube binary
      become: yes
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Installing kubectl
      command: minikube kubectl
    
    - name: Configure kubectl alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc" 
        line: "alias kubectl='minikube kubectl --'"          
        insertafter: EOF
      when: ansible_user != 'root'
      become: yes

