- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      

    - name: Install necessary packages
      apt:
        name: ca-certificates, curl, gnupg
        state: present
      

    - name: Create directory for GPG keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
      

    - name: Import Docker's GPG key
      command: apt-key add /etc/apt/keyrings/docker.gpg
      

    - name: Add Docker repository to Apt sources
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      

    - name: Update apt package cache (again)
      apt:
        update_cache: yes
      

    - name: Installing Docker packages
      apt:
        name:
          - docker          
          - docker.io
          - docker-registry
          - docker-compose
        state: present
      
    - name: Create the Docker group
      group:
        name: docker
        state: present

    - name: Add your user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Reset connection so docker group is picked up.
      meta: reset_connection     