apiVersion: v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    containers:
      - name: apache1
        image: httpd:alpine
        ports:
          - containerPort: 80
      