site_name: test-kubernetes

nav:
- Inici: index.md
- Proves en entorn local:
  - microk8s: local_test/microk8s.md
  - minikube: local_test/minikube.md
  - k0s: local_test/k0s.md
  - k3s: local_test/k3s.md
  - kind: local_test/kind.md
  - kubeadm: local_test/kubeadm.md
- Proves en entorn remot:
  - sd1: remote_test/sd1
  - sd2: remote_test/sd2
- Referències: references.md

theme:
  name: material
  icon:
    logo: material/test-tube
  custom_dir: docs/assets/images
  features:
  - navigation.top

  palette:
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/josanescod/tfg-kvbox

extra_css:
- stylesheets/extra.css

markdown_extensions:
- pymdownx.extra
- toc:
    title: Taula de continguts

