site_name: tfg-kubernetes

nav:
- Inici: index.md
- Proves realitzades:
  - minikube: tests/minikube.md
  - k3s: tests/k3s.md
  - kind: tests/kind.md
- Recursos de la API de k8s:
  - workloads: basic_concepts/workloads
  - serveis-ingress: basic_concepts/services_ingress
  - configuracions: basic_concepts/configurations
  - volums: basic_concepts/volumes
- Referències: references.md

theme:
  name: material
  icon:
    #logo: material/test-tube
    logo: material/kubernetes
  custom_dir: docs/assets/images

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/josanescod/tfg-kvbox

extra_css:
- stylesheets/extra.css

markdown_extensions:
- pymdownx.extra
