site_name: Proves tfg-kubernetes

nav:
    - Inici: index.md
    - Proves realitzades:
        - k3s: tests/k3s.md
        - k0s: tests/k0s.md
    - Referències: references.md
         
theme: material
extra:
  generator: false